<a href="https://colab.research.google.com/github/kmoh19/DataSCi/blob/master/DeepLearn/NLP--RNN_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import urllib

In [2]:
%tensorflow_version 2.x
import tensorflow as tf
tf.executing_eagerly()

TensorFlow 2.x selected.


True

In [0]:
path_to_file = "https://ocw.mit.edu/ans7870/6/6.006/s08/lecturenotes/files/t8.shakespeare.txt"

In [0]:
text=urllib.request.urlopen(path_to_file).readlines()
#text = open(path_to_file,'r').read()
text=[i.decode('utf-8') for i in text[252:124300]]
text="".join(text)


In [5]:
print(text[:100])

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose mig


In [0]:
vocab=sorted(set(text))

In [7]:
vocab

['\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}']

In [8]:
len(vocab)

84

In [0]:
char_to_ind ={char:ind for ind,char in enumerate(vocab)}

In [10]:
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '<': 23,
 '>': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '|': 82,
 '}': 83}

In [0]:
ind_to_char=np.array(vocab)

In [12]:
char_to_ind['I'],ind_to_char[33]

(34, 'H')

In [0]:
encoded_text=np.array([char_to_ind[c] for c in text])

In [14]:
encoded_text

array([ 1,  1,  1, ..., 80, 10,  0])

In [15]:
encoded_text.shape

(5441624,)

In [16]:
text[:500]

"                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bud"

In [17]:
encoded_text[:500]

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64, 73,
       60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,  1,
       59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,  0,
        1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57, 60,
       56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63, 75,
        1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76, 75,
        1, 56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63, 70,
       76, 67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60, 56,
       74, 60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,  1,
       63, 60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1, 63,
       64, 74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1,  1, 27, 76, 75,  1,
       75, 63, 70, 76,  1, 58, 70, 69, 75, 73, 56, 58, 75, 60, 59,  1, 75,
       70,  1, 75, 63, 64

### creating training batches

In [0]:
#on the average for shakespere there are 41 character per line...alternate lines rhyme
# to capture this we select 3 lines=120 characters...
seq_len=120

In [0]:
total_num_seq=len(text)//(seq_len+1)#integer division....+1 for zero indexing

In [20]:
total_num_seq

44972

In [0]:
#batch management function
char_dataset=tf.data.Dataset.from_tensor_slices(encoded_text)

In [22]:
type(char_dataset)

tensorflow.python.data.ops.dataset_ops.TensorSliceDataset

In [23]:
for item in char_dataset.take(50):
    print(item.numpy(),ind_to_char[item.numpy()])

1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
12 1
0 

1  
1  
31 F
73 r
70 o
68 m
1  
61 f
56 a
64 i
73 r
60 e
74 s
75 t
1  
58 c
73 r
60 e
56 a
75 t
76 u
73 r
60 e
74 s
1  
78 w
60 e


In [0]:
sequences = char_dataset.batch(seq_len+1,drop_remainder=True)#drop last remaining characters that cannot make up a sequence length

In [25]:
sequences

<BatchDataset shapes: (121,), types: tf.int64>

In [0]:
def create_seq_targets(seq):
    input_txt = seq[:-1] #hello my nam
    target_txt = seq[1:] #ello my name
    return input_txt,target_txt

In [0]:
dataset= sequences.map(create_seq_targets)

In [28]:
dataset

<MapDataset shapes: ((120,), (120,)), types: (tf.int64, tf.int64)>

In [29]:
for input_text,output_text in dataset.take(1):
    print(input_text.numpy())
    print("".join(ind_to_char[input_text.numpy()]))
    print("\n\n\n target seq \n\n\n")
    print(output_text.numpy())
    print("".join(ind_to_char[output_text.numpy()]))

[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 



 target seq 



[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1  1
 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1 78
 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63 56
 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60  1
 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1 56]
                    1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But a


In [0]:
batch_size = 128

In [0]:
#rebatching into 128 so we have 128 batches of 120 batches of input and target sequences!!! fantastic function
buffer_size =10000 # memory management...so that we dont shuffle whole all seqs in mem at once!
dataset =dataset.shuffle(buffer_size).batch(batch_size,drop_remainder=True) #we shuffle because we don't want to the model to learn a particular order i.e. we want to improve generalization...may or may not i guess...usecase specific

In [32]:
dataset

<BatchDataset shapes: ((128, 120), (128, 120)), types: (tf.int64, tf.int64)>

### building the model

In [0]:
vocab_size = len(vocab)

In [34]:
vocab_size

84

In [0]:
embed_dim = 64 # choose something in the same scale as your vocab_size--i think better smaller tha vocab_size

In [0]:
rnn_neurons = 1024

In [0]:
from tensorflow.keras.losses import sparse_categorical_crossentropy #? investigate

In [38]:
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module tensorflow.python.keras.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, axis=-1)



In [0]:
def sparse_cat_loss(y_true,y_pred):
    return sparse_categorical_crossentropy(y_true,y_pred,from_logits=True) # from logits=true because vocab is 1 hot encoded
# on further research i think it has to do with nature of input into the func... the same thing really
# https://stackoverflow.com/questions/41455101/what-is-the-meaning-of-the-word-logits-in-tensorflow

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,LSTM,Embedding,GRU

def create_model(vocab_size,embed_dim,rnn_neurons,batch_size):
    model =Sequential()
    model.add(Embedding(vocab_size,embed_dim,batch_input_shape=[batch_size,None]))
    model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))# research recommends glorot...also read help text on GRU object
    model.add(Dense(vocab_size))
    model.compile('adam',loss=sparse_cat_loss) # this is why we had to wrap sparse_categorical_crossentropy in a function...to change the from logit arg to True
    return model

In [0]:
model =create_model(vocab_size=vocab_size,embed_dim=embed_dim,
                    rnn_neurons=rnn_neurons,batch_size=batch_size)

In [42]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (128, None, 64)           5376      
_________________________________________________________________
gru (GRU)                    (128, None, 1024)         3348480   
_________________________________________________________________
dense (Dense)                (128, None, 84)           86100     
Total params: 3,439,956
Trainable params: 3,439,956
Non-trainable params: 0
_________________________________________________________________


In [0]:
#just testing model before training to see we have everything lined up right
for input_example_batch,target_example_batch in dataset.take(1):
  example_batch_predictions =model(input_example_batch)

In [47]:
example_batch_predictions.shape

TensorShape([128, 120, 84])

In [48]:
example_batch_predictions[0] # these are probabilities the model ouputs for characters in our vocab

<tf.Tensor: shape=(120, 84), dtype=float32, numpy=
array([[ 0.0025084 , -0.00144236, -0.0014917 , ...,  0.01476112,
        -0.00629725,  0.0021914 ],
       [-0.00170182,  0.00681937,  0.00352061, ...,  0.01420698,
        -0.0014509 ,  0.00148135],
       [-0.00468626,  0.00858257, -0.00057742, ...,  0.00433957,
         0.00254682,  0.00089825],
       ...,
       [-0.00180556, -0.00236609,  0.00255352, ..., -0.00218934,
         0.00089715, -0.00559134],
       [ 0.00065914, -0.00624004, -0.00580815, ..., -0.01274909,
         0.00342777, -0.00351468],
       [ 0.00450021, -0.00166791, -0.00686431, ..., -0.00689683,
         0.0064823 ,  0.00127538]], dtype=float32)>

In [0]:
sampled_indices=tf.random.categorical(example_batch_predictions[0],num_samples=1)

In [50]:
sampled_indices

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[25],
       [18],
       [28],
       [72],
       [83],
       [17],
       [81],
       [49],
       [52],
       [48],
       [26],
       [21],
       [55],
       [10],
       [37],
       [72],
       [ 6],
       [31],
       [68],
       [79],
       [ 3],
       [ 3],
       [81],
       [52],
       [63],
       [53],
       [56],
       [66],
       [33],
       [23],
       [20],
       [80],
       [ 2],
       [72],
       [73],
       [42],
       [71],
       [78],
       [75],
       [19],
       [47],
       [53],
       [ 6],
       [34],
       [63],
       [26],
       [56],
       [68],
       [70],
       [13],
       [71],
       [59],
       [75],
       [82],
       [61],
       [ 9],
       [67],
       [76],
       [40],
       [80],
       [48],
       [59],
       [55],
       [61],
       [41],
       [35],
       [53],
       [23],
       [64],
       [66],
       [75],
       [68],
       [ 4],
   

In [0]:
sampled_indices=tf.squeeze(sampled_indices,axis=-1).numpy()

In [52]:
sampled_indices

array([25, 18, 28, 72, 83, 17, 81, 49, 52, 48, 26, 21, 55, 10, 37, 72,  6,
       31, 68, 79,  3,  3, 81, 52, 63, 53, 56, 66, 33, 23, 20, 80,  2, 72,
       73, 42, 71, 78, 75, 19, 47, 53,  6, 34, 63, 26, 56, 68, 70, 13, 71,
       59, 75, 82, 61,  9, 67, 76, 40, 80, 48, 59, 55, 61, 41, 35, 53, 23,
       64, 66, 75, 68,  4, 67, 17, 40, 40, 37, 73, 17, 46, 78, 83, 63, 32,
       41, 81, 82, 53, 41,  4, 32,  8, 68, 63,  8, 63, 78,  3, 74,  8, 44,
       69, 78,  1, 59, 71, 78, 82, 14, 49, 82, 61, 41, 50, 78, 40,  4, 62,
        7])

In [54]:
ind_to_char[sampled_indices]

array(['?', '7', 'C', 'q', '}', '6', 'z', 'X', '[', 'W', 'A', ':', '`',
       '.', 'L', 'q', '(', 'F', 'm', 'x', '"', '"', 'z', '[', 'h', ']',
       'a', 'k', 'H', '<', '9', 'y', '!', 'q', 'r', 'Q', 'p', 'w', 't',
       '8', 'V', ']', '(', 'I', 'h', 'A', 'a', 'm', 'o', '2', 'p', 'd',
       't', '|', 'f', '-', 'l', 'u', 'O', 'y', 'W', 'd', '`', 'f', 'P',
       'J', ']', '<', 'i', 'k', 't', 'm', '&', 'l', '6', 'O', 'O', 'L',
       'r', '6', 'U', 'w', '}', 'h', 'G', 'P', 'z', '|', ']', 'P', '&',
       'G', ',', 'm', 'h', ',', 'h', 'w', '"', 's', ',', 'S', 'n', 'w',
       ' ', 'd', 'p', 'w', '|', '3', 'X', '|', 'f', 'P', 'Y', 'w', 'O',
       '&', 'g', ')'], dtype='<U1')

In [0]:
epochs=30
model.fit(dataset,epochs=epochs)

Train for 351 steps
Epoch 1/30
351/351 [==============================] - 2979s 8s/step - loss: 2.5356
Epoch 2/30
351/351 [==============================] - 3004s 9s/step - loss: 1.7840
Epoch 3/30
144/351 [===========>..................] - ETA: 29:55 - loss: 1.5565