In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import tensorflow as tf

In [3]:
path_to_file = "../../../FINAL-TF2-FILES/TF_2_Notebooks_and_Data/06-NLP-and-Text-Data/shakespeare.txt"

In [4]:
text = open(path_to_file,'r').read()

In [5]:
print(text[:1500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bud buriest thy content,
  And tender churl mak'st waste in niggarding:
    Pity the world, or else this glutton be,
    To eat the world's due, by the grave and thee.


                     2
  When forty winters shall besiege thy brow,
  And dig deep trenches in thy beauty's field,
  Thy youth's proud livery so gazed on now,
  Will be a tattered weed of small worth held:  
  Then being asked, where all thy beauty lies,
  Where all the treasure of thy lusty days;
  To say within thine own deep su

In [6]:
vocab=sorted(set(text))

In [7]:
vocab

['\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}']

In [8]:
len(vocab)

84

In [9]:
char_to_ind ={char:ind for ind,char in enumerate(vocab)}

In [10]:
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '<': 23,
 '>': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '|': 82,
 '}': 83}

In [11]:
ind_to_char=np.array(vocab)

In [12]:
char_to_ind['H'],ind_to_char[33]

(33, 'H')

In [13]:
encoded_text=np.array([char_to_ind[c] for c in text])

In [14]:
encoded_text

array([ 0,  1,  1, ..., 30, 39, 29])

In [15]:
encoded_text.shape

(5445609,)

In [16]:
text[:500]

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [17]:
encoded_text[:500]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75,  1, 56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63,
       70, 76, 67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60,
       56, 74, 60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,
        1, 63, 60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1,
       63, 64, 74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1,  1, 27, 76, 75,
        1, 75, 63, 70, 76,  1, 58, 70, 69, 75, 73, 56, 58, 75, 60, 59,  1,
       75, 70,  1, 75, 63

### creating training batches

In [18]:
#on the average for shakespere there are 41 character per line...alternate lines rhyme
# to capture this we select 3 lines=120 characters...
seq_len=120

In [19]:
total_num_seq=len(text)//(seq_len+1)#integer division....+1 for zero indexing

In [20]:
total_num_seq

45005

In [21]:
#batch management function
char_dataset=tf.data.Dataset.from_tensor_slices(encoded_text)

In [22]:
type(char_dataset)

tensorflow.python.data.ops.dataset_ops.TensorSliceDataset

In [23]:
for item in char_dataset.take(50):
    print(item.numpy(),ind_to_char[item.numpy()])

0 

1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
1  
12 1
0 

1  
1  
31 F
73 r
70 o
68 m
1  
61 f
56 a
64 i
73 r
60 e
74 s
75 t
1  
58 c
73 r
60 e
56 a
75 t
76 u
73 r
60 e
74 s
1  
78 w


In [24]:
sequences = char_dataset.batch(seq_len+1,drop_remainder=True)#drop last remaining characters that cannot make up a sequence length

In [25]:
sequences

<BatchDataset shapes: (121,), types: tf.int64>

In [26]:
def create_seq_targets(seq):
    input_txt = seq[:-1] #hello my nam
    target_txt = seq[1:] #ello my name
    return input_txt,target_txt

In [27]:
dataset= sequences.map(create_seq_targets)

In [28]:
dataset

<MapDataset shapes: ((120,), (120,)), types: (tf.int64, tf.int64)>

In [29]:
for input_text,output_text in dataset.take(1):
    print(input_text.numpy())
    print("".join(ind_to_char[input_text.numpy()]))
    print("\n\n\n target seq \n\n\n")
    print(output_text.numpy())
    print("".join(ind_to_char[output_text.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But



 target seq 



[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


In [30]:
batch_size = 128

In [31]:
#rebatching into 128 so we have 128 batches of 120 batches of input and target sequences!!! fantastic function
buffer_size =10000 # memory management...so that we dont shuffle whole all seqs in mem at once!
dataset =dataset.shuffle(buffer_size).batch(batch_size,drop_remainder=True) #we shuffle because we don't want to the model to learn a particular order i.e. we want to improve generalization...may or may not i guess...usecase specific

In [32]:
dataset

<BatchDataset shapes: ((128, 120), (128, 120)), types: (tf.int64, tf.int64)>

### building the model

In [33]:
vocab_size = len(vocab)

In [34]:
vocab_size

84

In [35]:
embed_dim = 64 # choose something in the same scale as your vocab_size--i think better smaller tha vocab_size

In [69]:
rnn_neurons = 1026

In [37]:
from tensorflow.keras.losses import sparse_categorical_crossentropy #? investigate

In [38]:
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module tensorflow.python.keras.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, axis=-1)



In [39]:
def sparse_cat_loss(y_true,y_pred):
    return sparse_categorical_crossentropy(y_true,y_pred,from_logits=True) # from logits=true because vocab is 1 hot encoded
# on further research i think it has to do with nature of input into the func... the same thing really
# https://stackoverflow.com/questions/41455101/what-is-the-meaning-of-the-word-logits-in-tensorflow

In [51]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,LSTM,Embedding,GRU

def create_model(vocab_size,embed_dim,rnn_neurons,batch_size):
    model =Sequential()
    model.add(Embedding(vocab_size,embed_dim,batch_input_shape=[batch_size,None]))
    model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))# research recommends glorot...also read help text on GRU object
    model.add(Dense(vocab_size))
    model.compile('adam',loss=sparse_cat_loss) # this is why we had to wrap sparse_categorical_crossentropy in a function...to change the from logit arg to True
    return model

In [52]:
model =create_model(vocab_size=vocab_size,embed_dim=embed_dim,
                    rnn_neurons=rnn_neurons,batch_size=batch_size)

In [53]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (128, None, 64)           5376      
_________________________________________________________________
gru_2 (GRU)                  (128, None, 1024)         3348480   
_________________________________________________________________
dense_2 (Dense)              (128, None, 84)           86100     
Total params: 3,439,956
Trainable params: 3,439,956
Non-trainable params: 0
_________________________________________________________________


In [54]:
#just testing model before training to see we have everything lined up right
for input_example_batch,target_example_batch in dataset.take(1):
      example_batch_predictions =model(input_example_batch)

In [55]:
example_batch_predictions.shape

TensorShape([128, 120, 84])

In [56]:
example_batch_predictions[0] # these are probabilities the model ouputs for characters in our vocab

<tf.Tensor: id=6000, shape=(120, 84), dtype=float32, numpy=
array([[ 0.00740766,  0.00097035,  0.0023639 , ...,  0.00101663,
         0.00191041,  0.00241909],
       [ 0.01124614, -0.00298158, -0.00456833, ..., -0.00011205,
         0.00049437,  0.00045863],
       [ 0.00534975, -0.00193671, -0.00354837, ..., -0.00039134,
         0.00323851,  0.00427392],
       ...,
       [ 0.00779642,  0.00081359, -0.00741041, ..., -0.00288446,
         0.00653564,  0.00350403],
       [ 0.00670649,  0.00581639, -0.00118448, ..., -0.00617621,
         0.00520406, -0.00125524],
       [ 0.01274673,  0.0050394 ,  0.00149776, ..., -0.00130982,
         0.00668019,  0.00225087]], dtype=float32)>

In [57]:
sampled_indices=tf.random.categorical(example_batch_predictions[0],num_samples=1)

In [58]:
sampled_indices=tf.squeeze(sampled_indices,axis=-1).numpy()

In [60]:
sampled_indices

array([33,  9, 82, 48, 66, 49, 68, 26, 42, 46, 14,  6, 27, 41, 24,  3, 74,
        9,  5, 82, 57, 22,  3,  8, 82, 49, 26, 23, 52, 16, 25,  5, 25,  8,
       62, 62, 81, 31, 10, 71, 32, 82, 82, 12, 51, 78, 61,  9, 78, 78, 70,
       13, 58, 78,  9, 25, 76, 36, 10, 65, 46, 35, 14, 16, 71,  7, 65,  3,
       75, 31, 57,  1,  4, 38, 12,  2, 70, 45, 28, 31, 53, 81, 56, 48, 15,
       32, 81, 62, 48, 37,  4, 49,  4, 26, 46, 72, 45, 15, 49,  0, 16, 49,
        0, 11, 35, 75, 25,  2, 57, 73, 59, 34, 39, 64, 78, 67, 23, 81, 44,
       83])

In [61]:
ind_to_char[sampled_indices]

array(['H', '-', '|', 'W', 'k', 'X', 'm', 'A', 'Q', 'U', '3', '(', 'B',
       'P', '>', '"', 's', '-', "'", '|', 'b', ';', '"', ',', '|', 'X',
       'A', '<', '[', '5', '?', "'", '?', ',', 'g', 'g', 'z', 'F', '.',
       'p', 'G', '|', '|', '1', 'Z', 'w', 'f', '-', 'w', 'w', 'o', '2',
       'c', 'w', '-', '?', 'u', 'K', '.', 'j', 'U', 'J', '3', '5', 'p',
       ')', 'j', '"', 't', 'F', 'b', ' ', '&', 'M', '1', '!', 'o', 'T',
       'C', 'F', ']', 'z', 'a', 'W', '4', 'G', 'z', 'g', 'W', 'L', '&',
       'X', '&', 'A', 'U', 'q', 'T', '4', 'X', '\n', '5', 'X', '\n', '0',
       'J', 't', '?', '!', 'b', 'r', 'd', 'I', 'N', 'i', 'w', 'l', '<',
       'z', 'S', '}'], dtype='<U1')

In [ ]:
epochs=30
model.fit(dataset,epochs=epochs) # get some GPUs!...then save model to an appropriate location

In [84]:
# saving model
model.save('nlp_shakespeare.h5')

### loading saved model

In [63]:
from tensorflow.keras.models import load_model

In [76]:
model = create_model(vocab_size,embed_dim,rnn_neurons,batch_size=1)
model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_10 (Embedding)     (1, None, 64)             5376      
_________________________________________________________________
gru_7 (GRU)                  (1, None, 1026)           3361176   
_________________________________________________________________
dense_7 (Dense)              (1, None, 84)             86268     
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [79]:
model.load_weights('../../../FINAL-TF2-FILES/TF_2_Notebooks_and_Data/06-NLP-and-Text-Data/shakespeare_gen.h5')

In [80]:
model.build(tf.TensorShape([1,None]))# for accepting just 1 batch (for predicting) vs original 128 

In [81]:
model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_10 (Embedding)     (1, None, 64)             5376      
_________________________________________________________________
gru_7 (GRU)                  (1, None, 1026)           3361176   
_________________________________________________________________
dense_7 (Dense)              (1, None, 84)             86268     
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [82]:
def generate_text(model,start_seed,gen_size=500,temp=1.0):
    num_generate=gen_size
    input_eval = [char_to_ind[s] for s in start_seed]
    input_eval = tf.expand_dims(input_eval,0)
    text_generated = []
    temperature = temp
    model.reset_states()
    
    for i in range(num_generate):
        predictions = model(input_eval)
        predictions = tf.squeeze(predictions,0) #to undo the expand_dims before the loop
        predictions = predictions/temperature
        predicted_id = tf.random.categorical(predictions,num_samples=1)[-1,0].numpy()
        input_eval =tf.expand_dims([predicted_id],0)
        text_generated.append(ind_to_char[predicted_id])
    return (start_seed+"".join(text_generated))

In [86]:
print(generate_text(model, "thou art",gen_size=1000))

thou art much than four things
    That comes for money by these question.
    Come, sirs.             Exeunt with tongue and hiss and letter]
  ULYSSES. Why, this profane young zitch! y good Dantastirable cross,
    And bring these tedious.
  ALCIBIADES. Sirs, hold that firm.
  PAINTER. Ay, an. And, fame.
  LUCIUS. Alas, sir, no more wreckles all my tongue;
    My name, and what sad they saw his cradl
    must approve ma, yet subscribe, an and be you
but to be ashould
    thundear him.
  BASSANIO. This fertidimish windows breaking,
    I wish you further, being held, by this,
    Reproach all faith and weeps, and lowly sweetly.               Exeunt




SCENE II.
V. 'Twas of all confidence.
   Y. O, behold'!
    Urre  PEMBROKE. Pray this: my mother was ill to the Tubove, on the
    Willow-ganner. Come, Avenobstillol, I was wasted?
  IAGO.                        Exit white the noftiness
    Seeks not too much for ever; that a double news
    OR FOR MEMBERSHIP.>>



ACT II. SCENE I.
Sici